package actions

import (
	"github.com/abdev/fabcar-extended/web_app/models"
	"github.com/gobuffalo/buffalo"
	"github.com/gobuffalo/pop"
	"github.com/pkg/errors"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (CarLog)
// DB Table: Plural (car_logs)
// Resource: Plural (CarLogs)
// Path: Plural (/car_logs)
// View Template Folder: Plural (/templates/car_logs/)

// CarLogsResource is the resource for the CarLog model
type CarLogsResource struct {
	buffalo.Resource
}

// List gets all CarLogs. This function is mapped to the path
// GET /car_logs
func (v CarLogsResource) List(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	carLogs := &models.CarLogs{}

	// Paginate results. Params "page" and "per_page" control pagination.
	// Default values are "page=1" and "per_page=20".
	q := tx.PaginateFromParams(c.Params()).Order("submitted_on DESC")

	// Retrieve all CarLogs from the DB
	if err := q.All(carLogs); err != nil {
		return errors.WithStack(err)
	}

	// Add the paginator to the context so it can be used in the template.
	c.Set("pagination", q.Paginator)

	return c.Render(200, r.Auto(c, carLogs))
}

// Show gets the data for one CarLog. This function is mapped to
// the path GET /car_logs/{car_log_id}
func (v CarLogsResource) Show(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty CarLog
	carLog := &models.CarLog{}

	// To find the CarLog the parameter car_log_id is used.
	if err := tx.Find(carLog, c.Param("car_log_id")); err != nil {
		return c.Error(404, err)
	}

	return c.Render(200, r.Auto(c, carLog))
}

// New renders the form for creating a new CarLog.
// This function is mapped to the path GET /car_logs/new
func (v CarLogsResource) New(c buffalo.Context) error {
	return c.Render(200, r.Auto(c, &models.CarLog{}))
}

// Create adds a CarLog to the DB. This function is mapped to the
// path POST /car_logs
func (v CarLogsResource) Create(c buffalo.Context) error {
	// Allocate an empty CarLog
	carLog := &models.CarLog{}

	// Bind carLog to the html form elements
	if err := c.Bind(carLog); err != nil {
		return errors.WithStack(err)
	}

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Validate the data from the html form
	verrs, err := tx.ValidateAndCreate(carLog)
	if err != nil {
		return errors.WithStack(err)
	}

	if verrs.HasAny() {
		// Make the errors available inside the html template
		c.Set("errors", verrs)

		// Render again the new.html template that the user can
		// correct the input.
		return c.Render(422, r.Auto(c, carLog))
	}

	// If there are no errors set a success message
	c.Flash().Add("success", "CarLog was created successfully")

	// and redirect to the car_logs index page
	return c.Render(201, r.Auto(c, carLog))
}

// Edit renders a edit form for a CarLog. This function is
// mapped to the path GET /car_logs/{car_log_id}/edit
func (v CarLogsResource) Edit(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty CarLog
	carLog := &models.CarLog{}

	if err := tx.Find(carLog, c.Param("car_log_id")); err != nil {
		return c.Error(404, err)
	}

	return c.Render(200, r.Auto(c, carLog))
}

// Update changes a CarLog in the DB. This function is mapped to
// the path PUT /car_logs/{car_log_id}
func (v CarLogsResource) Update(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty CarLog
	carLog := &models.CarLog{}

	if err := tx.Find(carLog, c.Param("car_log_id")); err != nil {
		return c.Error(404, err)
	}

	// Bind CarLog to the html form elements
	if err := c.Bind(carLog); err != nil {
		return errors.WithStack(err)
	}

	verrs, err := tx.ValidateAndUpdate(carLog)
	if err != nil {
		return errors.WithStack(err)
	}

	if verrs.HasAny() {
		// Make the errors available inside the html template
		c.Set("errors", verrs)

		// Render again the edit.html template that the user can
		// correct the input.
		return c.Render(422, r.Auto(c, carLog))
	}

	// If there are no errors set a success message
	c.Flash().Add("success", "CarLog was updated successfully")

	// and redirect to the car_logs index page
	return c.Render(200, r.Auto(c, carLog))
}

// Destroy deletes a CarLog from the DB. This function is mapped
// to the path DELETE /car_logs/{car_log_id}
func (v CarLogsResource) Destroy(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty CarLog
	carLog := &models.CarLog{}

	// To find the CarLog the parameter car_log_id is used.
	if err := tx.Find(carLog, c.Param("car_log_id")); err != nil {
		return c.Error(404, err)
	}

	if err := tx.Destroy(carLog); err != nil {
		return errors.WithStack(err)
	}

	// If there are no errors set a flash message
	c.Flash().Add("success", "CarLog was destroyed successfully")

	// Redirect to the car_logs index page
	return c.Render(200, r.Auto(c, carLog))
}
